### ISSUE TITLE
Creating a Kernel fails if csdf has ppm as unit or one line of the simulation "amp" contains only zeros.

### ISSUE THREAD

**Issue by N1gh7h4wk** [DeepanshS/mrinversion#3]
When i was altering the input file for the MAF example, the line 
`K = sidebands.kernel(supersampling=1)`
returned an array of NaN values. 

When investigating, I found the 
https://github.com/DeepanshS/mrinversion/blob/785002052b064d5d50235ab6b6f46a40240ad7f2/mrinversion/kernel/csa_aniso.py#L107 to return zeros, if the .csdf data file contains ppm instead of frequency units.

After fixing that issue by presenting my data in the .csdf data file as Hz, i still got the return values of nan and inf in K, which stems from one vector inside the amp values that only contains zeros,
https://github.com/DeepanshS/mrinversion/blob/785002052b064d5d50235ab6b6f46a40240ad7f2/mrinversion/kernel/base.py#L72 divides then by those zeros.

**Comment by DeepanshS** [comment]
Hello @N1gh7h4wk, 

You are correct that when the csdm dimension of the input dataset contains ppm units, the returned Kernel is incorrect. I'll work on fixing this bug.

For your second point, a csdm dimension in units of Hz should generate a correct kernel. In the examples, I use the variable ``anisotroic_dimension`` to hold the csdm dimension along the anisotropic dimension. Can you share the output of ``print(anisotropic_dimension)``? It will help with the debugging.

**Comment by DeepanshS** [comment]
@N1gh7h4wk  The issue with the incorrect kernel resulting from the csdm dimension object with ppm units should be fixed in #4. Instead of raising error or user warning, I convert the ppm units to frequency units by multiplying the dimension with the Larmor frequency. The Larmor frequency is the product of the negative gyromagnetic ratio of the nucleus and the macroscopic external magnetic field, both of which are the input arguments of the ShieldingPALineshape class.

For your second point, I am not able to reproduce the error. Could you share a minimal reproducible code?

**Comment by N1gh7h4wk** [comment]
Okay I reproduced this issue:
print(anisotropic_dimension) yields:
[https://pastebin.com/SCCGyAJf](url)
otherwise I am using the same setup as in the Example files:

`# %%
# **x-y dimensions:**
# The two inverse dimensions corresponding to the `x` and `y`-axis of the `x`-`y` grid.
inverse_dimensions = [
    cp.LinearDimension(count=20, increment="5000 Hz", label="x"),  # the `x`-dimension.
    cp.LinearDimension(count=20, increment="5000 Hz", label="y"),  # the `y`-dimension.
]`

`# %%
# Generating the kernel
# '''''''''''''''''''''
#
# For MAF/PASS datasets, the kernel corresponds to the pure nuclear shielding anisotropy
# sideband spectra. Use the
# :class:`~mrinversion.kernel.nmr.ShieldingPALineshape` class to generate a
# shielding spinning sidebands kernel.
sidebands = ShieldingPALineshape(
    anisotropic_dimension=anisotropic_dimension,
    inverse_dimension=inverse_dimensions,
    channel="125Te",
    magnetic_flux_density="11.7 T",
    rotor_angle="54.735°",
    rotor_frequency="10000 Hz",
    number_of_sidebands=anisotropic_dimension.count,
)`

`#%%
K = sidebands.kernel(supersampling=1)
print(K.shape)
# data_object_truncate=data_object_truncate.transpose()
# print(K.dtype)
print(K)`
With the last call resulting in the error and a K full of NaN and +-inf.
While i believe this to be a poor choice of parameters, it can happen. I found this occur because of the "normalization" by K that searches row wise, while one (the first) row of amp is returned as zeros only.

`mrinversion/mrinversion/kernel/base.py:72: RuntimeWarning: invalid value encountered in true_divide
  K /= K[tuple(section)].sum()`
I did not test it with your most recent PR, but I assume that one is about Datasets with ppm values only. For testing this i converted my data to Hz values and then using the Hz to ppm conversion as in the examples.

print(amp) in the _averaged_kernel method where the above error occurs afterwards returns:
[https://pastebin.com/PFi859p7](url)
with print(amp)[0] being only zeros.
I have been able to cicumvent this by either catching a line of zeros before the normalization step, or simply altering the input parameters (like inverse_dimension and the size of anisotropic_dimension) a bit.

**Comment by DeepanshS** [comment]
@N1gh7h4wk Thanks for the code. In your comment, the output for the ``anisotropic_dimension`` is a link for the issue page. Could you paste the text in the comment? I believe the problem might be originating from how the anisotropic dimension is defined in the csdf dataset. The rest of your code, ``inverse_dimensions``, and ``sidebands`` kernel are set up correctly.

In the following snippet of code, I assume the anisotropic dimension as a sideband dimension with 32 sidebands and 10 kHz increment (same as the rotor_frequency) and generate the kernel with no error.
```
anisotropic_dimension = cp.LinearDimension(count=32, increment='10000 Hz', complex_fft=True)

inverse_dimensions = [ 
    cp.LinearDimension(count=20, increment="5000 Hz", label="x"), # thex-dimension. 
    cp.LinearDimension(count=20, increment="5000 Hz", label="y"), # the y-dimension. 
]

sidebands = ShieldingPALineshape(
    anisotropic_dimension=anisotropic_dimension, inverse_dimension=inverse_dimensions, 
    channel="125Te", magnetic_flux_density="11.7 T", rotor_angle="54.735°", 
    rotor_frequency="10000 Hz", number_of_sidebands=anisotropic_dimension.count
)

K = sidebands.kernel(supersampling=1)
```

Note, if I define the anisotropic dimension as
```
anisotropic_dimension_1 = cp.LinearDimension(count=32, increment='10000 Hz')
```
that is, without the ``complex_fft=True``, I get a ``RuntimeWarning: invalid value encountered in true_divide
  K /= K[tuple(section)].sum()``

The difference is that a dimension with ``complex_fft=True`` have coordinates
```
print(anisotropic_dimension.coordinates)
[-160000. -150000. -140000. -130000. -120000. -110000. -100000.  -90000.
  -80000.  -70000.  -60000.  -50000.  -40000.  -30000.  -20000.  -10000.
       0.   10000.   20000.   30000.   40000.   50000.   60000.   70000.
   80000.   90000.  100000.  110000.  120000.  130000.  140000.  150000.] Hz
```
which is likely the coordinates for a sideband dimension, while the dimension without ``complex_fft=True`` have coordinates
```
print(anisotropic_dimension_1.coordinates)
[     0.  10000.  20000.  30000.  40000.  50000.  60000.  70000.  80000.
  90000. 100000. 110000. 120000. 130000. 140000. 150000. 160000. 170000.
 180000. 190000. 200000. 210000. 220000. 230000. 240000. 250000. 260000.
 270000. 280000. 290000. 300000. 310000.] Hz
```
The ``complex_fft`` flag is a quick way to tell that the dimension coordinates are a result of a complex FFT, which put the zero at the center of the dimension.

**Comment by N1gh7h4wk** [comment]
So i updated the links, I mistakenly put the url into the text field and vice versa. So my anisotropic dimension was not centered at 0, so i will try using the  `complex_fft=True` option or right away re-reference my data to zero in the middle of the spectrum. This is then not a bug.

Closing this, thank you for the reply

**Comment by DeepanshS** [comment]
Hello @N1gh7h4wk. I wanted to check in if you were able to use the library and invert the PASS spectrum. Let me know if I can assist in any way or if there is something I can do to improve the documentation. I appreciate your input.

Thanks.
